import "./globals.css";

import "@css/animate.css";
import "@css/bootstrap.min.css";
import "@css/font-awesome.css";
import "@css/magnific-popup.css";
import "@css/meanmenu.css";
import "@css/nice-select.css";
import "@css/swiper-bundle.min.css";
import "@css/main.css";

import { DM_Sans, Montserrat } from "next/font/google";

const montserratFont = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-montserrat",
});

const dm_sansFont = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-dm-sans",
});

export const metadata = {
  title: "NetSec InfoTech - IT Solutions & Technology",
  description:
    "Generated by NetSec InfoTech - IT Solutions & Technology",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${montserratFont.variable} ${dm_sansFont.variable}`}
    >
      <head>
        <base href="/" />
      </head>
      <body>{children}</body>
    </html>
  );
}
